---
title: Installing Vaadin Spreadsheet
order: 5
layout: page
---

[[spreadsheet.installation.general]]
= Installing Vaadin Spreadsheet

You can download and install Spreadsheet from Vaadin Directory at
link:https://vaadin.com/addon/vaadin-spreadsheet[vaadin.com/addon/vaadin-spreadsheet]
as an installation package, or get it with Maven or Ivy. You can get Pro 
subscription at link:https://vaadin.com/pro[vaadin.com/pro].

For general instructions on installing add-ons, please see
https://vaadin.com/docs/v8/framework/addons/addons-overview#addons.overview[Installing Add-ons]. 
This add-on includes both a widget set and a theme, so you
need to compile the widget sets and themes in your project.

ifdef::web[]
[[spreadsheet.installation]]
== Installing Dependencies
[[spreadsheet.installation.ivy]]
=== For Ivy Users

If you use the add-on in an Eclipse project created with the Vaadin Plugin for
Eclipse, you can define an Ivy dependency to automatically download the library.
Include the following declaration inside the [literal]#++dependencies++# section
in the [filename]#ivy.xml#:

[subs="normal"]
----
&lt;dependency org="com.vaadin"
            name="vaadin-spreadsheet"
            rev="[replaceable]#latest.release#"
            conf="default-+++&gt;+++default" /&gt;
----
You can use the [literal]#++latest.release++# revision tag to always use the latest
release or (preferably) specify a version by its version number. IvyDE should
resolve the dependency immediately as you save the file. See
link:https://vaadin.com/docs/v8/framework/addons/addons-eclipse#addons.eclipse["Installing Add-ons in Eclipse with Ivy"] for further details.

endif::web[]

ifdef::web[]
[[spreadsheet.installation.maven]]
=== For Maven Users

You can install Vaadin Spreadsheet in a Maven project by adding it as a
dependency, you need to include the following dependency in the POM. The
[literal]#++artifactId++# should be [literal]#++vaadin-spreadsheet++#.

[subs="normal"]
----
&lt;dependency&gt;
    &lt;groupId&gt;com.vaadin&lt;/groupId&gt;
    &lt;artifactId&gt;vaadin-spreadsheet&lt;/artifactId&gt;
    &lt;version&gt;[replaceable]##LATEST##&lt;/version&gt;
&lt;/dependency&gt;
----
You can use the [parameter]#LATEST# version as shown above or (preferably) a
specific version by its version number.

You also need to define the repository for the Vaadin add-ons under the
[literal]#++<repositories>++# element:

----
<repository>
    <id>vaadin-addons</id>
    <url>https://maven.vaadin.com/vaadin-addons</url>
</repository>
----

Finally, you need to enable the widget set compilation in the POM, as described
in <<dummy/../../framework/addons/addons-maven#addons.maven.widgetset,"Enabling
Widget Set Compilation">>, and compile it.

endif::web[]

ifdef::web[]
[[spreadsheet.installation.downloading]]
=== For Users Without Dependency Management Tools

Vaadin Spreadsheet is distributed as a Zip package that contains the Spreadsheet
JAR, a JavaDoc JAR, and other documentation. You can download the
Zip package from Vaadin Directory.

More information about Vaadin Commercial License and Service 
Terms is available link:https://vaadin.com/commercial-license-and-service-terms[here].

The [filename]#vaadin-spreadsheet-&lt;version&gt;.jar#, as well as all the dependency
libraries in the [filename]#lib# folder, should be put in the
[filename]#WEB-INF/lib# folder of the web application.

The [filename]#vaadin-spreadsheet-&lt;version&gt;-sources.jar# and
[filename]#vaadin-spreadsheet-&lt;version&gt;-javadoc.jar# are development libraries
that should not normally be deployed with the web application, so you should put
them to a separate non-deployment folder. In Eclipse projects, this is usually a
[filename]#lib# sub-folder in the project folder.

If you intend to use Vaadin TestBench for testing your Spreadsheet, you will
benefit from the Vaadin Spreadsheet TestBench API libraries included in the
[filename]#testbench-api# folder. They should be copied to a non-deployment
library folder in the project.

Please see the [filename]#README.html# for more information about the package
contents.

endif::web[]

[[spreadsheet.installing.license]]
== Installing a License Key

You need to install a license key for Vaadin Charts before compiling the widget set.
The license key is checked during widget set compilation, so you do not need it when deploying the application. See link:https://vaadin.com/pricing[pricing] for obtaining a Pro subscription.

You can download Vaadin Charts from the
link:https://vaadin.com/directory/component/vaadin-charts[Vaadin Charts download page] in Vaadin Directory.

You need to install a license key before compiling the widget set. The license
key is checked during widget set compilation, so you do not need it when
deploying the application. See link:https://vaadin.com/pricing[pricing] for 
obtaining a Pro subscription.

You can download Vaadin Spreadsheet from the
link:https://vaadin.com/directory/component/vaadin-spreadsheet[Vaadin Spreadsheet download page] in Vaadin Directory.

See link:https://vaadin.com/docs/v8/framework/addons/addons-cval["Installing Commercial Vaadin Add-on Licenses"] for detailed instructions on obtaining and
installing the license key.


[[spreadsheet.installation.widgetset]]
== Compiling the Widget Set

Compile the widget set as instructed in link:https://vaadin.com/docs/v8/framework/addons/addons-maven#compiling-the-widget-set["Compiling the Widget Set"]. 
Widget set compilation should automatically update
your project widget set to include the Spreadsheet widget set:


----
<inherits name="com.vaadin.addon.spreadsheet.Widgetset"/>
----

If you have set the widget set to be manually edited, you need to add the
element yourself.


[[spreadsheet.installation.theme]]
== Compiling Theme

Compile the theme as instructed in
link:https://vaadin.com/docs/v8/framework/themes/themes-compiling["Compiling Sass Themes"]. 
If you compile in Eclipse or with Maven, the [filename]#addons.scss#
file in your theme should be automatically updated to include the Spreadsheet
theme:


----
@import "../../../VAADIN/addons/spreadsheet/spreadsheet.scss";
@mixin addons {
	 @include spreadsheet;
}
----

If you are compiling the theme otherwise, or the theme addons are not
automatically updated for some reason, you need to add the statements yourself.


[[spreadsheet.installation.demo]]
== Importing the Demo

The Demo, illustrated in
link:https://vaadin.com/docs/v8/spreadsheet/spreadsheet-overview#spreadsheet.overview.demo["Demo for Vaadin Spreadsheet"] 
in the overview, showcases most of the functionality
in Vaadin Spreadsheet. You can try out the demo online at
link:http://demo.vaadin.com/spreadsheet[demo.vaadin.com/spreadsheet] or check the sources
from the link:https://github.com/vaadin/spreadsheet[GitHub page].
